source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '11.0'

target :ZSWTappableLabel_Example do
  pod "ZSWTappableLabel", :path => "../"
  pod 'ZSWTaggedString', '~> 4.0'
  pod 'ZSWTaggedString/Swift', '~> 4.0'
  pod 'SnapKit'
  pod 'Masonry'

  target 'Tests' do
    inherit! :search_paths
    pod 'Specta'
    pod 'Expecta'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end

